# Generated by Django 4.0.6 on 2022-08-18 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ranking',
            options={'ordering': ['time']},
        ),
        migrations.AddField(
            model_name='ranking',
            name='user_ip',
            field=models.CharField(default='0.0.0.0', max_length=100),
        ),
    ]
